"""create zones table (metadata mirror)

Revision ID: a2c0d44c0c59
Revises: c474afac5a70
Create Date: 2026-09-11 13:45:57.213729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c0d44c0c59'
down_revision: Union[str, Sequence[str], None] = 'c474afac5a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('parent_type', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_zones_parent', 'zones', ['parent_type', 'parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_zones_parent', table_name='zones')
    op.drop_table('zones')
    # ### end Alembic commands ###
